//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistema_PetsEntities : DbContext
    {
        public Sistema_PetsEntities()
            : base("name=Sistema_PetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesos> Accesos { get; set; }
        public virtual DbSet<Categoria_Productos> Categoria_Productos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Factura_Producto> Factura_Producto { get; set; }
        public virtual DbSet<Facturación> Facturación { get; set; }
        public virtual DbSet<Factura_Producto1> Factura_Producto1 { get; set; }
        public virtual DbSet<Lotes> Lotes { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Tipo_Cliente> Tipo_Cliente { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Tipo_Trabajador> Tipo_Trabajador { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    }
}
