//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturación
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturación()
        {
            this.Factura_Producto = new HashSet<Factura_Producto>();
            this.Factura_Producto1 = new HashSet<Factura_Producto1>();
        }
    
        public string Factura_Id { get; set; }
        public double Descuento { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public string NIT_Cliente { get; set; }
        public double Efectivo { get; set; }
        public double Tarjeta { get; set; }
        public decimal Total { get; set; }
        public double Cheque { get; set; }
        public Nullable<int> Empleado_Id { get; set; }
        public Nullable<int> Cliente_Id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Producto> Factura_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Producto1> Factura_Producto1 { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
