//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura_Producto
    {
        public string FacturaProd_Id { get; set; }
        public int Cantidad { get; set; }
        public double SubTotal { get; set; }
        public string Factura_Id { get; set; }
        public Nullable<int> Productos_Id { get; set; }
    
        public virtual Facturación Facturación { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
