//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public int Id_Lotes { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha_Caducidad { get; set; }
        public System.DateTime Fecha_Produccion { get; set; }
        public Nullable<int> Productos_Id { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
