//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Factura_Producto = new HashSet<Factura_Producto>();
            this.Factura_Producto1 = new HashSet<Factura_Producto1>();
            this.Lotes = new HashSet<Lotes>();
        }
    
        public int Productos_Id { get; set; }
        public string Nombre_Producto { get; set; }
        public double Descuento { get; set; }
        public double PreciosinDecuento { get; set; }
        public string Unidad_de_medida { get; set; }
        public bool Habilitar { get; set; }
        public Nullable<int> Tipo_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Producto> Factura_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Producto1> Factura_Producto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lotes> Lotes { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
    }
}
